CREATE TABLE university.departamentos(
	COD_DPTO NUMERIC(3) UNIQUE NOT NULL,
  	NOME_DPTO VARCHAR(50),
  	CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY(COD_DPTO)
);

CREATE TABLE university.cursos(
	COD_CURSO NUMERIC(4) UNIQUE NOT NULL,
  	NOM_CURSO VARCHAR(80),
  	COD_DPTO NUMERIC(3) NOT NULL,
  	CONSTRAINT CUR_PK PRIMARY KEY(COD_CURSO),
  	CONSTRAINT CUR_DEP_FK FOREIGN KEY(COD_DPTO) 
  	REFERENCES university.departamentos(COD_DPTO)
);

CREATE TABLE university.disciplinas(
	COD_DISC NUMERIC(5) UNIQUE NOT NULL,
  	NOME_DISC VARCHAR(80),
  	CARGA_HORARIA NUMERIC(5,2),
  	CONSTRAINT DISC_PK PRIMARY KEY(COD_DISC)
);

CREATE TABLE university.matrizes_cursos(
	COD_CURSO NUMERIC(4) NOT NULL,
  	COD_DISC NUMERIC(5) NOT NULL,
  	PERIODO NUMERIC(2),
  	CONSTRAINT MCU_CUR_FK FOREIGN KEY(COD_CURSO) 
  	REFERENCES university.cursos(COD_CURSO),
  	CONSTRAINT MCU_DIS_FK FOREIGN KEY(COD_DISC)
  	REFERENCES university.disciplinas(COD_DISC),
  	CONSTRAINT MCU_PK PRIMARY KEY(COD_CURSO,COD_DISC)
);


CREATE TABLE university.alunos(
	MAT_ALU NUMERIC(10) UNIQUE NOT NULL,
  	NOME VARCHAR(100),
  	DAT_ENTRADA DATE, 
  	COD_CURSO NUMERIC(4) NOT NULL,
  	COTISTA CHAR(1),
  	CONSTRAINT ALU_PK PRIMARY KEY(MAT_ALU),
  	CONSTRAINT ALU_CUR_FK FOREIGN KEY (COD_CURSO) 
  	REFERENCES university.cursos(COD_CURSO)
);

CREATE TABLE university.matriculas(
	SEMESTRE NUMERIC(6),
  	MAT_ALU NUMERIC(10) NOT NULL,
  	COD_DISC NUMERIC(5) NOT NULL,
  	NOTA NUMERIC(5,2),
  	FALTAS NUMERIC(3),
  	STATUS CHAR(1),
  	CONSTRAINT MAT_ALU_FK FOREIGN KEY(MAT_ALU) 
  	REFERENCES university.alunos(MAT_ALU),
  	CONSTRAINT MAT_DIS_FK FOREIGN KEY(COD_DISC)
  	REFERENCES university.disciplinas(COD_DISC),
  	CONSTRAINT MAT_PK PRIMARY KEY(MAT_ALU,SEMESTRE)
);
